apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: kind-ai-dev
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 17964
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 17988
        listenAddress: "127.0.0.1"
        protocol: TCP
      - containerPort: 443
        hostPort: 17943
        listenAddress: "127.0.0.1"
        protocol: TCP
      - containerPort: 17900
        hostPort: 17900
        protocol: TCP
      - containerPort: 17901
        hostPort: 17901
        protocol: TCP
      - containerPort: 17980
        hostPort: 17980
        protocol: TCP
      - containerPort: 17981
        hostPort: 17981
        protocol: TCP
      - containerPort: 17982
        hostPort: 17982
        protocol: TCP
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            service-node-port-range: 17900-17999
      - |
        kind: KubeletConfiguration
        config:
          nodeStatusUpdateFrequency: 10s
    extraMounts:
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock
