scan_timeout = 500
command_timeout = 1000

format = """
$directory\
$git_branch\
${custom.git_status_compact}\
$character"""

[directory]
style = "bold cyan"

[character]
success_symbol = "[❯](bold white)"
error_symbol = "[✖](bold red)"
vimcmd_symbol = "[❮](bold cyan)"

[git_branch]
format = "[git:$branch]($style) "
style = "bold magenta"
